export const GET_DB_FILE = 'GET_DB_FILE';
export const DB_FILE_READY = 'DB_FILE_READY';
export const WRITE_DB_DATA = 'WRITE_DB_DATA';
export const INIT_WS_CLIENT = 'INIT_WS_CLIENT';
export const RUN_BUSYBEE_TEST = 'RUN_BUSYBEE_TEST';
export const BUSYBEE_MSG = 'BUSYBEE_MSG';

export default {
  GET_DB_FILE,
  DB_FILE_READY,
  WRITE_DB_DATA,
  INIT_WS_CLIENT,
  RUN_BUSYBEE_TEST,
  BUSYBEE_MSG
}